Repository spinnaker/spinnaker, pull requests merged in 2025-05, with the labels that each got.

#7066 fix(config): fix the issue of halyard failing to add docker registry account
  halyard/halyard-config/halyard-config.gradle
  halyard/halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/dockerRegistry/DockerRegistryAccountValidator.java
  halyard/halyard-config/src/test/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/dockerRegistry/DockerRegistryAccountValidatorTest.java
Labels: ready to merge, auto merged

#7060 fix(retrofit2): fix the issue of retrofit2 being unable to convert the Event object to RequestBody.
  igor-core/src/test/java/com/netflix/spinnaker/igor/history/EchoServiceTest.java
  igor/igor-core/igor-core.gradle
  igor/igor-core/src/main/java/com/netflix/spinnaker/igor/history/EchoConverterFactory.java
  igor/igor-core/src/main/java/com/netflix/spinnaker/igor/history/EchoService.java
  igor/igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/EchoConfig.groovy
  igor/igor-web/src/test/java/com/netflix/spinnaker/igor/nexus/NexusEventPosterTest.java
Labels: ready to merge, auto merged

#7061 chore(core): upgrade to TypeScript 5.x
  deck/package.json
  deck/packages/amazon/package.json
  deck/packages/amazon/src/serverGroup/configure/wizard/pages/ServerGroupCapacity.tsx
  deck/packages/amazon/src/serverGroup/configure/wizard/pages/ServerGroupInstanceType.tsx
  deck/packages/app/package.json
  deck/packages/app/src/canary/canary/CanaryScore.tsx
  deck/packages/appengine/package.json
  deck/packages/azure/package.json
  deck/packages/cloudfoundry/package.json
  deck/packages/core/package.json
  deck/packages/core/src/config/VersionChecker.tsx
  deck/packages/core/src/notification/NotificationsList.tsx
  deck/packages/core/src/pipeline/config/validation/PipelineConfigValidator.ts
  deck/packages/core/src/presentation/forms/FormikForm.tsx
  deck/packages/core/src/utils/index.ts
  deck/packages/core/src/utils/parseNum.ts
  deck/packages/docker/package.json
  deck/packages/ecs/package.json
  deck/packages/eslint-plugin/base.config.js
  deck/packages/eslint-plugin/package.json
  deck/packages/eslint-plugin/rules/api-deprecation.ts
  deck/packages/eslint-plugin/rules/import-from-presentation-not-core.ts
  deck/packages/eslint-plugin/rules/import-sort.ts
  deck/packages/eslint-plugin/rules/migrate-to-mock-http-client.ts
  deck/packages/eslint-plugin/utils/ast.ts
  deck/packages/google/package.json
  deck/packages/kubernetes/package.json
  deck/packages/kubernetes/src/serverGroup/details/resize/resize.controller.ts
  deck/packages/mocks/package.json
  deck/packages/oracle/package.json
  deck/packages/pluginsdk-peerdeps/package.json
  deck/packages/pluginsdk/package.json
  deck/packages/presentation/package.json
  deck/packages/tencentcloud/package.json
  deck/packages/titus/package.json
  deck/yarn.lock
Labels: ready to merge, auto merged

#7071 Auto-merge of individual repos (main)
  deck/packages/core/src/navigation/UrlBuilder.ts
  echo/echo-core/src/main/java/com/netflix/spinnaker/echo/notification/AbstractEventNotificationAgent.java
  echo/echo-core/src/test/groovy/com/netflix/spinnaker/echo/notification/AbstractEventNotificationAgentSpec.groovy
  fiat/fiat-google-groups/src/main/java/com/netflix/spinnaker/fiat/roles/google/GoogleDirectoryUserRolesProvider.java
  fiat/fiat-google-groups/src/test/groovy/com/netflix/spinnaker/fiat/roles/google/GoogleDirectoryUserRolesProviderSpec.groovy
Labels: no-squash

#7073 fix(docker): fix the issue of fetching docker images
  clouddriver/clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClient.groovy
  clouddriver/clouddriver-docker/src/test/java/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClientTest.java
Labels: ready to merge, auto merged

#7077 fix(web): fix HelmConverterFactory for deserialization error
  igor/igor-web/igor-web.gradle
  igor/igor-web/src/main/java/com/netflix/spinnaker/igor/config/HelmConverterFactory.java
  igor/igor-web/src/test/java/com/netflix/spinnaker/igor/helm/accounts/HelmAccountsServiceTest.java
Labels: ready to merge

#7078 feat(kayenta): adding outlierStrategy field in metric config modal
  deck-kayenta/package.json
  deck-kayenta/src/kayenta/actions/creators.ts
  deck-kayenta/src/kayenta/actions/index.ts
  deck-kayenta/src/kayenta/canary.help.ts
  deck-kayenta/src/kayenta/edit/editMetricModal.spec.tsx
  deck-kayenta/src/kayenta/edit/editMetricModal.tsx
  deck-kayenta/src/kayenta/reducers/selectedConfig.ts
Labels: ready to merge, auto merged

#7069 feat(helm/image): Adding kork-docker extracting functionality from clouddriver-docker
  clouddriver/clouddriver-docker/clouddriver-docker.gradle
  clouddriver/clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/auth/DockerBearerTokenService.groovy
  clouddriver/clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClient.groovy
  clouddriver/clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/exception/DockerRegistryOperationException.groovy
  clouddriver/clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/agent/DockerRegistryImageCachingAgent.groovy
  clouddriver/clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryCredentials.groovy
  clouddriver/clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryCredentialsInitializer.groovy
  clouddriver/clouddriver-docker/src/main/groovy/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryNamedAccountCredentials.groovy
  clouddriver/clouddriver-docker/src/main/java/com/netflix/spinnaker/config/DockerRegistryConfiguration.java
  clouddriver/clouddriver-docker/src/test/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/auth/DockerBearerTokenServiceSpec.groovy
  clouddriver/clouddriver-docker/src/test/groovy/com/netflix/spinnaker/clouddriver/docker/registry/api/v2/client/DockerRegistryClientSpec.groovy
  clouddriver/clouddriver-docker/src/test/groovy/com/netflix/spinnaker/clouddriver/docker/registry/provider/agent/DockerRegistryImageCachingAgentTest.groovy
  clouddriver/clouddriver-docker/src/test/java/com/netflix/spinnaker/clouddriver/docker/registry/health/DockerRegistryHealthIndicatorTest.java
  clouddriver/clouddriver-docker/src/test/java/com/netflix/spinnaker/clouddriver/docker/registry/security/DockerRegistryNamedAccountCredentialsTest.java
  halyard/halyard-config/halyard-config.gradle
  halyard/halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/dockerRegistry/DockerRegistryAccountValidator.java
  halyard/halyard-config/src/test/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/dockerRegistry/DockerRegistryAccountValidatorTest.java
  kork/kork-docker/kork-docker.gradle
  kork/kork-docker/src/main/java/com/netflix/spinnaker/kork/docker/exceptions/DockerRegistryAuthenticationException.java
  kork/kork-docker/src/main/java/com/netflix/spinnaker/kork/docker/exceptions/DockerRegistryOperationException.java
  kork/kork-docker/src/main/java/com/netflix/spinnaker/kork/docker/model/DockerBearerToken.java
  kork/kork-docker/src/main/java/com/netflix/spinnaker/kork/docker/model/DockerConfig.java
  kork/kork-docker/src/main/java/com/netflix/spinnaker/kork/docker/model/DockerLayer.java
  kork/kork-docker/src/main/java/com/netflix/spinnaker/kork/docker/model/DockerManifest.java
  kork/kork-docker/src/main/java/com/netflix/spinnaker/kork/docker/model/DockerRegistryCatalog.java
  kork/kork-docker/src/main/java/com/netflix/spinnaker/kork/docker/model/DockerRegistryTags.java
  kork/kork-docker/src/main/java/com/netflix/spinnaker/kork/docker/security/TrustAllX509TrustManager.java
  kork/kork-docker/src/main/java/com/netflix/spinnaker/kork/docker/service/DefaultDockerOkClientProvider.java
  kork/kork-docker/src/main/java/com/netflix/spinnaker/kork/docker/service/DockerBearerTokenService.java
  kork/kork-docker/src/main/java/com/netflix/spinnaker/kork/docker/service/DockerOkClientProvider.java
  kork/kork-docker/src/main/java/com/netflix/spinnaker/kork/docker/service/DockerRegistryClient.java
  kork/kork-docker/src/main/java/com/netflix/spinnaker/kork/docker/service/DockerUserAgent.java
  kork/kork-docker/src/main/java/com/netflix/spinnaker/kork/docker/service/RegistryService.java
  kork/kork-docker/src/test/java/com/netflix/spinnaker/kork/docker/service/DockerBearerTokenServiceTest.java
  kork/kork-docker/src/test/java/com/netflix/spinnaker/kork/docker/service/DockerRegistryClientTest.java
  kork/kork-docker/src/test/resources/password.txt
  kork/settings.gradle
Labels: ready to merge, auto merged

#7080 fix(build): Update top-level versions.yml metadata if release is newest
  .github/actions/spinnaker-release/dist/index.js
  .github/actions/spinnaker-release/src/bom/changelog.ts
  .github/actions/spinnaker-release/src/bom/versionsDotYml.ts
  .github/actions/spinnaker-release/src/util.ts
  .github/actions/spinnaker-release/src/versions.ts
Labels: ready to merge

#7049 chore(test): adjust test code to execute on arm
  clouddriver/clouddriver-artifacts/src/integration/resources/clouddriver.yml
  clouddriver/clouddriver-ecs/src/integration/resources/clouddriver.yml
  clouddriver/clouddriver-kubernetes/src/integration/java/com/netflix/spinnaker/clouddriver/kubernetes/it/containers/KubernetesCluster.java
  clouddriver/clouddriver-kubernetes/src/integration/resources/clouddriver.yml
  front50/front50-sql/src/test/kotlin/com/netflix/spinnaker/front50/model/SqlStorageServiceTests.kt
  kork/kork-sql-test/src/main/java/com/netflix/spinnaker/kork/sql/test/SqlTestUtil.java
  kork/kork-sql/src/test/java/com/netflix/spinnaker/kork/sql/config/TransactionIsolationMysqlTest.java
Labels: ready to merge, auto merged
